<a href="https://colab.research.google.com/github/iharshidas/LetsUpgradePython/blob/master/Day3_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### **Questions 1:**
Create a numpy array starting from 2 till 50 with a stepsize of 3.


In [2]:
import numpy as np
lst=[i for i in range(2,51,3)]
a=np.array(lst)
print(a)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47 50]


### **Questions 2:**
Accept two lists of 5 elements each from the user.
Convert them to numpy arrays. Concatenate these arrays and print it. Also sort these arrays and print it.


In [6]:
lst=[]
lst2=[]

# List 1
for i in range(5):
  a=int(input())
  lst.append(a)

# List 2
for i in range(5):
  a=int(input())
  lst2.append(a)

arr=np.array(lst)
arr2=np.array(lst2)
print(arr)
print(arr2)

b=np.array(lst+lst2)
print(b)

b.sort()
print(b)

5
4
3
2
1
0
9
8
7
6
[5 4 3 2 1]
[0 9 8 7 6]
[5 4 3 2 1 0 9 8 7 6]
[0 1 2 3 4 5 6 7 8 9]


### **Questions 3:**
Write a code snippet to find the dimensions of a ndarray and its size.


In [11]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a.shape)
print(a.size)

(3, 3)
9


### **Questions 4:**
How to convert a 1D array into a 2D array? Demonstrate with the help of a code snippet.  
Hint: np.newaxis, np.expand_dims

In [20]:
a=np.array([1,2,3,4,5,6,7,8,9])
print(a[np.newaxis,:])
print(np.expand_dims(a,axis=0))

[[1 2 3 4 5 6 7 8 9]]
[[1 2 3 4 5 6 7 8 9]]


### **Questions 5:**
Consider two square numpy arrays. Stack them vertically and horizontally.  
Hint: Use vstack(), hstack()


In [29]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
b=np.array([[11,22,33],[44,55,66],[77,88,99]])
print(np.vstack((a,b)))
print()
print(np.hstack((a,b)))

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [11 22 33]
 [44 55 66]
 [77 88 99]]

[[ 1  2  3 11 22 33]
 [ 4  5  6 44 55 66]
 [ 7  8  9 77 88 99]]


### **Questions 6:**
How to get unique items and counts of unique items?

In [19]:
a=np.random.randint(0,10,7)
print(a)
(val,count)=np.unique(a,return_counts=True)
print(np.asarray((val,count)).T)

[2 1 8 8 8 7 4]
[[1 1]
 [2 1]
 [4 1]
 [7 1]
 [8 3]]
